CREATE TABLE IF NOT EXISTS departments (department_id VARCHAR(30) PRIMARY KEY, department_code VARCHAR(30), department_name VARCHAR(160), manager_employee_id VARCHAR(30), hse_contact_id VARCHAR(30), location VARCHAR(160), active BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS zones (zone_id VARCHAR(30) PRIMARY KEY, zone_code VARCHAR(30), zone_name VARCHAR(160), name_ar VARCHAR(160), name_en VARCHAR(160), department_id VARCHAR(30), risk_level VARCHAR(20), restricted_access BOOLEAN DEFAULT FALSE, active BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS employees (employee_id VARCHAR(30) PRIMARY KEY, employee_code VARCHAR(30), display_name VARCHAR(160), full_name VARCHAR(160), email VARCHAR(190), phone VARCHAR(40), job_title VARCHAR(120), department_id VARCHAR(30), manager_id VARCHAR(30), employment_type VARCHAR(30), status VARCHAR(20), hire_date DATE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users (user_id INT PRIMARY KEY AUTO_INCREMENT, employee_id VARCHAR(30), username VARCHAR(255) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, status_id INT NOT NULL DEFAULT 1, mfa_enabled TINYINT(1) DEFAULT 0, last_login_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS roles (role_id INT PRIMARY KEY AUTO_INCREMENT, role_name VARCHAR(60) NOT NULL, description VARCHAR(255), scope_level VARCHAR(60));
CREATE TABLE IF NOT EXISTS user_roles (assignment_id INT PRIMARY KEY AUTO_INCREMENT, user_id INT, role_id INT, scope_type_id INT, scope_id VARCHAR(40), valid_from DATE, valid_to DATE, status_id INT DEFAULT 1);
CREATE TABLE IF NOT EXISTS mfa_codes (mfa_code_id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, code_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP NOT NULL, expires_at TIMESTAMP NOT NULL, used_flag BOOLEAN DEFAULT FALSE, attempt_count INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS user_avatars (user_id INT PRIMARY KEY, file_name VARCHAR(255) NOT NULL, file_path VARCHAR(500) NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS profile_edit_history (history_id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, field_name VARCHAR(80) NOT NULL, old_value VARCHAR(1000), new_value VARCHAR(1000), modified_at TIMESTAMP NOT NULL);


CREATE TABLE IF NOT EXISTS permit_types (permit_type_id INT PRIMARY KEY, name VARCHAR(60), description VARCHAR(255));
CREATE TABLE IF NOT EXISTS permit_statuses (permit_status_id INT PRIMARY KEY, name VARCHAR(60), description VARCHAR(255));
CREATE TABLE IF NOT EXISTS permit_risk_levels (permit_risk_level_id INT PRIMARY KEY, name VARCHAR(60), description VARCHAR(255));
CREATE TABLE IF NOT EXISTS permit_gas_tests (test_id INT PRIMARY KEY AUTO_INCREMENT, permit_id VARCHAR(40), test_time TIMESTAMP, o2_pct DECIMAL(5,2), lel_pct DECIMAL(5,2), h2s_ppm DECIMAL(5,2), co_ppm DECIMAL(5,2), tester_employee_id VARCHAR(40), result VARCHAR(20));
CREATE TABLE IF NOT EXISTS approver_roles (approver_role_id INT PRIMARY KEY, name VARCHAR(60));
CREATE TABLE IF NOT EXISTS approval_decisions (approval_decision_id INT PRIMARY KEY, name VARCHAR(60));
CREATE TABLE IF NOT EXISTS permit_approvals (approval_id INT PRIMARY KEY AUTO_INCREMENT, permit_id INT, step_no INT, approver_role_id INT, approver_id INT, decision_id INT, decided_at TIMESTAMP, comments CLOB, signature_hash VARCHAR(255), status_id INT);

MERGE INTO approver_roles KEY(approver_role_id) VALUES (1, 'REQUESTER'), (2, 'AREA_SUPERVISOR'), (3, 'HSE_OFFICER'), (4, 'HSE_MANAGER');
MERGE INTO approval_decisions KEY(approval_decision_id) VALUES (1, 'PENDING'), (2, 'APPROVED'), (3, 'REJECTED');
CREATE TABLE IF NOT EXISTS simops (simops_id INT PRIMARY KEY AUTO_INCREMENT, zone_id VARCHAR(40), permit_a_id VARCHAR(40), permit_b_id VARCHAR(40), conflict_type VARCHAR(60), distance_m DECIMAL(6,2), decision VARCHAR(255), status VARCHAR(30));

CREATE TABLE IF NOT EXISTS jsa_statuses (jsa_status_id INT PRIMARY KEY, name VARCHAR(60), description VARCHAR(255));
CREATE TABLE IF NOT EXISTS jsa_frequencies (jsa_frequency_id INT PRIMARY KEY, name VARCHAR(60), description VARCHAR(255));
CREATE TABLE IF NOT EXISTS control_levels (control_level_id INT PRIMARY KEY, name VARCHAR(60), description VARCHAR(255));
CREATE TABLE IF NOT EXISTS jsa (jsa_id INT PRIMARY KEY AUTO_INCREMENT, task_name VARCHAR(255), zone_id INT, created_by INT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, frequency_id INT, permit_required TINYINT(1) DEFAULT 1, permit_type VARCHAR(60), inherent_score INT, residual_score INT, status_id INT DEFAULT 3, approved_by INT, approved_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS jsa_steps (step_id INT PRIMARY KEY AUTO_INCREMENT, jsa_id INT, step_no INT, task_step CLOB, hazard CLOB, control_level_id INT, control_measure CLOB, likelihood_before INT, severity_before INT, score_before DECIMAL(12,2), likelihood_after INT, severity_after INT, score_after DECIMAL(12,2), responsible_role VARCHAR(255));

MERGE INTO jsa_statuses KEY(jsa_status_id) VALUES (1, 'DRAFT', 'Draft'), (2, 'PENDING_APPROVAL', 'Pending Approval'), (3, 'APPROVED', 'Approved'), (4, 'REJECTED', 'Rejected'), (5, 'ARCHIVED', 'Archived');
MERGE INTO jsa_frequencies KEY(jsa_frequency_id) VALUES (1, 'DAILY', 'Daily'), (2, 'WEEKLY', 'Weekly'), (3, 'MONTHLY', 'Monthly'), (4, 'QUARTERLY', 'Quarterly'), (5, 'ANNUAL', 'Annual'), (6, 'AS_NEEDED', 'As Needed');
MERGE INTO control_levels KEY(control_level_id) VALUES (1, 'ELIMINATION', 'Elimination'), (2, 'SUBSTITUTION', 'Substitution'), (3, 'ENGINEERING', 'Engineering Controls'), (4, 'ADMINISTRATIVE', 'Administrative Controls'), (5, 'PPE', 'Personal Protective Equipment');
CREATE TABLE IF NOT EXISTS permits (permit_id VARCHAR(40) PRIMARY KEY, permit_type VARCHAR(50), permit_type_id INT, department_id VARCHAR(30), zone_id VARCHAR(30), work_description CLOB, requester_id VARCHAR(30), issuer_id VARCHAR(30), executor_type VARCHAR(30), executor_type_id INT, executor_name VARCHAR(160), start_at TIMESTAMP, expiry_at TIMESTAMP, risk_level VARCHAR(20), risk_level_id INT, jsa_id VARCHAR(40), status VARCHAR(30), status_id INT, suspended_reason CLOB, actual_close_at TIMESTAMP, hours_to_expiry DECIMAL(12,2), automation_flag TINYINT DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS risk_register (risk_id VARCHAR(40) PRIMARY KEY, department_id VARCHAR(30), zone_id VARCHAR(30), hazard VARCHAR(240), activity VARCHAR(240), likelihood INT, severity INT, inherent_score INT, risk_level VARCHAR(20), controls CLOB, residual_likelihood INT, residual_severity INT, residual_score INT, owner_id VARCHAR(30), status VARCHAR(30), last_reviewed_at DATE, next_review_date DATE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS inspections (inspection_id VARCHAR(40) PRIMARY KEY, inspection_type VARCHAR(60), title VARCHAR(200), department_id VARCHAR(30), zone_id VARCHAR(30), inspector_id VARCHAR(30), scheduled_at TIMESTAMP, completed_at TIMESTAMP, score DECIMAL(5,2), status VARCHAR(30), notes CLOB, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS inspection_findings (finding_id VARCHAR(40) PRIMARY KEY, inspection_id VARCHAR(40), category VARCHAR(80), description CLOB, severity VARCHAR(20), status VARCHAR(30), photo_url VARCHAR(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS capa (capa_id VARCHAR(40) PRIMARY KEY, incident_id VARCHAR(40), finding_id VARCHAR(40), title VARCHAR(200), action_type VARCHAR(30), priority VARCHAR(20), assigned_to VARCHAR(30), due_date DATE, status VARCHAR(30), completion_date DATE, verification_status VARCHAR(30), verified_by VARCHAR(30), last_reminder_at TIMESTAMP, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS chemical_statuses (chemical_status_id INT PRIMARY KEY, name VARCHAR(60));
CREATE TABLE IF NOT EXISTS sds_record_statuses (sds_record_status_id INT PRIMARY KEY, name VARCHAR(60));
CREATE TABLE IF NOT EXISTS chemicals (chemical_id INT PRIMARY KEY AUTO_INCREMENT, trade_name VARCHAR(255), chemical_name VARCHAR(255), cas_number VARCHAR(255), supplier VARCHAR(255), quantity DECIMAL(12,2), unit VARCHAR(255), ghs_classes VARCHAR(255), storage_class VARCHAR(60), zone_id INT, status_id INT DEFAULT 1);
CREATE TABLE IF NOT EXISTS sds_records (sds_id INT PRIMARY KEY AUTO_INCREMENT, chemical_id INT, version_no VARCHAR(255), issue_date DATE, expiry_date DATE, language VARCHAR(255), file_ref VARCHAR(255), emergency_summary CLOB, status_id INT DEFAULT 1, days_to_expiry DECIMAL(12,2));

MERGE INTO chemical_statuses KEY(chemical_status_id) VALUES (1, 'ACTIVE'), (2, 'PHASED_OUT'), (3, 'QUARANTINED');
MERGE INTO sds_record_statuses KEY(sds_record_status_id) VALUES (1, 'CURRENT'), (2, 'DUE_SOON'), (3, 'EXPIRED'), (4, 'MISSING_CURRENT_VERSION');
CREATE TABLE IF NOT EXISTS health_exams (exam_id VARCHAR(40) PRIMARY KEY, employee_id VARCHAR(30), exam_type VARCHAR(80), exam_date DATE, next_exam_date DATE, fitness_status VARCHAR(40), restrictions CLOB, provider VARCHAR(160), status VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS training_courses (course_id VARCHAR(40) PRIMARY KEY, course_code VARCHAR(40), course_name VARCHAR(180), validity_months INT, provider VARCHAR(160), mandatory BOOLEAN, active BOOLEAN, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS certificates (certificate_id VARCHAR(40) PRIMARY KEY, employee_id VARCHAR(30), course_id VARCHAR(40), issue_date DATE, expiry_date DATE, certificate_number VARCHAR(80), provider VARCHAR(160), status VARCHAR(30), last_reminder_at TIMESTAMP, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notifications (notification_id VARCHAR(50) PRIMARY KEY, recipient_user_id VARCHAR(40), recipient_employee_id VARCHAR(30), type VARCHAR(60), title VARCHAR(200), message CLOB, entity_type VARCHAR(40), entity_id VARCHAR(50), status VARCHAR(20), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, read_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_log (audit_id VARCHAR(50) PRIMARY KEY, actor_type VARCHAR(30), actor_type_id INT, actor_id VARCHAR(80), action VARCHAR(80), entity_type VARCHAR(50), entity_name VARCHAR(50), entity_id VARCHAR(80), diff_json CLOB, details_json CLOB, result_id INT, ip_or_source VARCHAR(80), correlation_id VARCHAR(80), immutable_hash VARCHAR(255), occurred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS automation_rules (rule_id VARCHAR(40) PRIMARY KEY, rule_name VARCHAR(160), entity_type VARCHAR(40), trigger_type VARCHAR(40), schedule_cron VARCHAR(80), conditions_json CLOB, action_type VARCHAR(60), action_endpoint VARCHAR(255), active BOOLEAN, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS automation_actions (action_record_id VARCHAR(50) PRIMARY KEY, event_id VARCHAR(50) UNIQUE, idempotency_key VARCHAR(100) UNIQUE, rule_id VARCHAR(40), entity_type VARCHAR(40), entity_id VARCHAR(80), action VARCHAR(80), alert_code VARCHAR(80), status VARCHAR(30), payload_json CLOB, processed_at_utc TIMESTAMP DEFAULT CURRENT_TIMESTAMP, audit_id VARCHAR(50));
CREATE TABLE IF NOT EXISTS sensor_events (sensor_event_id VARCHAR(50) PRIMARY KEY, sensor_type VARCHAR(60), zone_id VARCHAR(30), reading_value DECIMAL(14,4), reading_unit VARCHAR(30), threshold_value DECIMAL(14,4), alert_level VARCHAR(20), source VARCHAR(30), recorded_at TIMESTAMP, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

MERGE INTO permit_types KEY(permit_type_id) VALUES (1, 'HOT_WORK', 'Hot Work and Welding'), (2, 'ELECTRICAL', 'Electrical Work and Isolation'), (3, 'WORK_AT_HEIGHT', 'Work at Height and Scaffolding'), (4, 'CONFINED_SPACE', 'Confined Space Entry'), (5, 'MECHANICAL_LOTO', 'Mechanical Isolation and LOTO'), (6, 'EXCAVATION', 'Excavation and Digging'), (7, 'RADIOGRAPHY', 'Industrial Radiography');
MERGE INTO permit_statuses KEY(permit_status_id) VALUES (1, 'DRAFT', 'Draft'), (2, 'PENDING_APPROVAL', 'Pending Approval'), (3, 'ACTIVE', 'Active and Approved'), (4, 'SUSPENDED', 'Suspended'), (5, 'REJECTED', 'Rejected'), (6, 'CLOSED', 'Closed'), (7, 'CANCELLED', 'Cancelled');
MERGE INTO permit_risk_levels KEY(permit_risk_level_id) VALUES (1, 'LOW', 'Low Risk'), (2, 'MEDIUM', 'Medium Risk'), (3, 'HIGH', 'High Risk'), (4, 'CRITICAL', 'Critical Risk');
MERGE INTO zones KEY(zone_id) VALUES ('1', 'ZON-01', 'Accessory Production Line A', 'خط الإنتاج A', 'Line A', 'DEP-01', 'HIGH', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('8', 'ZON-08', 'Dispatch Area', 'منطقة الشحن', 'Dispatch Area', 'DEP-02', 'MEDIUM', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('ZON-01', 'ZON-01', 'Accessory Production Line A', 'خط الإنتاج A', 'Line A', 'DEP-01', 'HIGH', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
MERGE INTO employees KEY(employee_id) VALUES ('1', 'EMP-001', 'م. مصطفى', 'Mostafa Mohamed', 'mostafa@esca.com', '0100000001', 'HSE Manager', 'DEP-01', NULL, 'PERMANENT', 'ACTIVE', CURRENT_DATE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('EMP-001', 'EMP-001', 'م. مصطفى', 'Mostafa Mohamed', 'mostafa@esca.com', '0100000001', 'HSE Manager', 'DEP-01', NULL, 'PERMANENT', 'ACTIVE', CURRENT_DATE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


