CREATE TABLE IF NOT EXISTS departments (department_id VARCHAR(30) PRIMARY KEY, department_code VARCHAR(30), department_name VARCHAR(160), manager_employee_id VARCHAR(30), hse_contact_id VARCHAR(30), location VARCHAR(160), active BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS zones (zone_id VARCHAR(30) PRIMARY KEY, zone_code VARCHAR(30), zone_name VARCHAR(160), department_id VARCHAR(30), risk_level VARCHAR(20), restricted_access BOOLEAN DEFAULT FALSE, active BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS employees (employee_id VARCHAR(30) PRIMARY KEY, employee_code VARCHAR(30), display_name VARCHAR(160), full_name VARCHAR(160), email VARCHAR(190), phone VARCHAR(40), job_title VARCHAR(120), department_id VARCHAR(30), manager_id VARCHAR(30), employment_type VARCHAR(30), status VARCHAR(20), hire_date DATE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users (user_id INT PRIMARY KEY AUTO_INCREMENT, employee_id VARCHAR(30), username VARCHAR(255) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, status_id INT NOT NULL DEFAULT 1, mfa_enabled TINYINT(1) DEFAULT 0, last_login_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS roles (role_id INT PRIMARY KEY AUTO_INCREMENT, role_name VARCHAR(60) NOT NULL, description VARCHAR(255), scope_level VARCHAR(60));
CREATE TABLE IF NOT EXISTS user_roles (assignment_id INT PRIMARY KEY AUTO_INCREMENT, user_id INT, role_id INT, scope_type_id INT, scope_id VARCHAR(40), valid_from DATE, valid_to DATE, status_id INT DEFAULT 1);


CREATE TABLE IF NOT EXISTS incidents (incident_id VARCHAR(40) PRIMARY KEY, incident_type VARCHAR(40), title VARCHAR(200), description CLOB, department_id VARCHAR(30), zone_id VARCHAR(30), reported_by VARCHAR(30), occurred_at TIMESTAMP, severity VARCHAR(20), status VARCHAR(30), immediate_action CLOB, root_cause CLOB, lost_time_days INT DEFAULT 0, closed_at TIMESTAMP, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS jsa (jsa_id VARCHAR(40) PRIMARY KEY, title VARCHAR(200), activity VARCHAR(240), department_id VARCHAR(30), zone_id VARCHAR(30), prepared_by VARCHAR(30), hazards CLOB, controls CLOB, required_ppe CLOB, risk_level VARCHAR(20), status VARCHAR(30), approved_by VARCHAR(30), approved_at TIMESTAMP, review_date DATE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS permits (permit_id VARCHAR(40) PRIMARY KEY, permit_type VARCHAR(50), department_id VARCHAR(30), zone_id VARCHAR(30), work_description CLOB, requester_id VARCHAR(30), issuer_id VARCHAR(30), executor_type VARCHAR(30), executor_name VARCHAR(160), start_at TIMESTAMP, expiry_at TIMESTAMP, risk_level VARCHAR(20), jsa_id VARCHAR(40), status VARCHAR(30), suspended_reason CLOB, actual_close_at TIMESTAMP, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS risk_register (risk_id VARCHAR(40) PRIMARY KEY, department_id VARCHAR(30), zone_id VARCHAR(30), hazard VARCHAR(240), activity VARCHAR(240), likelihood INT, severity INT, inherent_score INT, risk_level VARCHAR(20), controls CLOB, residual_likelihood INT, residual_severity INT, residual_score INT, owner_id VARCHAR(30), status VARCHAR(30), last_reviewed_at DATE, next_review_date DATE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS inspections (inspection_id VARCHAR(40) PRIMARY KEY, inspection_type VARCHAR(60), title VARCHAR(200), department_id VARCHAR(30), zone_id VARCHAR(30), inspector_id VARCHAR(30), scheduled_at TIMESTAMP, completed_at TIMESTAMP, score DECIMAL(5,2), status VARCHAR(30), notes CLOB, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS inspection_findings (finding_id VARCHAR(40) PRIMARY KEY, inspection_id VARCHAR(40), category VARCHAR(80), description CLOB, severity VARCHAR(20), status VARCHAR(30), photo_url VARCHAR(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS capa (capa_id VARCHAR(40) PRIMARY KEY, incident_id VARCHAR(40), finding_id VARCHAR(40), title VARCHAR(200), action_type VARCHAR(30), priority VARCHAR(20), assigned_to VARCHAR(30), due_date DATE, status VARCHAR(30), completion_date DATE, verification_status VARCHAR(30), verified_by VARCHAR(30), last_reminder_at TIMESTAMP, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS chemicals (chemical_id VARCHAR(40) PRIMARY KEY, chemical_name VARCHAR(180), cas_number VARCHAR(60), department_id VARCHAR(30), zone_id VARCHAR(30), quantity DECIMAL(12,3), unit VARCHAR(20), hazard_class VARCHAR(80), storage_requirements CLOB, sds_url VARCHAR(500), expiry_date DATE, status VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS health_exams (exam_id VARCHAR(40) PRIMARY KEY, employee_id VARCHAR(30), exam_type VARCHAR(80), exam_date DATE, next_exam_date DATE, fitness_status VARCHAR(40), restrictions CLOB, provider VARCHAR(160), status VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS training_courses (course_id VARCHAR(40) PRIMARY KEY, course_code VARCHAR(40), course_name VARCHAR(180), validity_months INT, provider VARCHAR(160), mandatory BOOLEAN, active BOOLEAN, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS certificates (certificate_id VARCHAR(40) PRIMARY KEY, employee_id VARCHAR(30), course_id VARCHAR(40), issue_date DATE, expiry_date DATE, certificate_number VARCHAR(80), provider VARCHAR(160), status VARCHAR(30), last_reminder_at TIMESTAMP, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notifications (notification_id VARCHAR(50) PRIMARY KEY, recipient_user_id VARCHAR(40), recipient_employee_id VARCHAR(30), type VARCHAR(60), title VARCHAR(200), message CLOB, entity_type VARCHAR(40), entity_id VARCHAR(50), status VARCHAR(20), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, read_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_log (audit_id VARCHAR(50) PRIMARY KEY, actor_type VARCHAR(30), actor_id VARCHAR(80), action VARCHAR(80), entity_type VARCHAR(50), entity_id VARCHAR(80), details_json CLOB, correlation_id VARCHAR(80), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS automation_rules (rule_id VARCHAR(40) PRIMARY KEY, rule_name VARCHAR(160), entity_type VARCHAR(40), trigger_type VARCHAR(40), schedule_cron VARCHAR(80), conditions_json CLOB, action_type VARCHAR(60), action_endpoint VARCHAR(255), active BOOLEAN, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS automation_actions (action_record_id VARCHAR(50) PRIMARY KEY, event_id VARCHAR(50) UNIQUE, idempotency_key VARCHAR(100) UNIQUE, rule_id VARCHAR(40), entity_type VARCHAR(40), entity_id VARCHAR(80), action VARCHAR(80), alert_code VARCHAR(80), status VARCHAR(30), payload_json CLOB, processed_at_utc TIMESTAMP DEFAULT CURRENT_TIMESTAMP, audit_id VARCHAR(50));
CREATE TABLE IF NOT EXISTS sensor_events (sensor_event_id VARCHAR(50) PRIMARY KEY, sensor_type VARCHAR(60), zone_id VARCHAR(30), reading_value DECIMAL(14,4), reading_unit VARCHAR(30), threshold_value DECIMAL(14,4), alert_level VARCHAR(20), source VARCHAR(30), recorded_at TIMESTAMP, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
